//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarkovPriceViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarkovPriceViewer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version is newest..
        /// </summary>
        public static string CurrentVersionNewest {
            get {
                return ResourceManager.GetString("CurrentVersionNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergo.
        /// </summary>
        public static string Ergo {
            get {
                return ResourceManager.GetString("Ergo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flea.
        /// </summary>
        public static string Flea {
            get {
                return ResourceManager.GetString("Flea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version ({0}) found. Please download new version. Current Version is {1}.
        /// </summary>
        public static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found on Flea..
        /// </summary>
        public static string NoFlea {
            get {
                return ResourceManager.GetString("NoFlea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for loading data. Please check your Internet, and check Tarkov wiki site..
        /// </summary>
        public static string NotFinishLoading {
            get {
                return ResourceManager.GetString("NotFinishLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Left : {1}.
        /// </summary>
        public static string OverlayCompareTxt {
            get {
                return ResourceManager.GetString("OverlayCompareTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barters &amp; Crafts :.
        /// </summary>
        public static string OverlayInfoBartersNCraft {
            get {
                return ResourceManager.GetString("OverlayInfoBartersNCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy From Trader : {0}.
        /// </summary>
        public static string OverlayInfoBuyFromTrader {
            get {
                return ResourceManager.GetString("OverlayInfoBuyFromTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy From Trader Price : {0}.
        /// </summary>
        public static string OverlayInfoBuyFromTraderPrice {
            get {
                return ResourceManager.GetString("OverlayInfoBuyFromTraderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Price : {0}.
        /// </summary>
        public static string OverlayInfoDayPrice {
            get {
                return ResourceManager.GetString("OverlayInfoDayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Price : {0} ({1}).
        /// </summary>
        public static string OverlayInfoLastPrice {
            get {
                return ResourceManager.GetString("OverlayInfoLastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : {0}.
        /// </summary>
        public static string OverlayInfoName {
            get {
                return ResourceManager.GetString("OverlayInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs :.
        /// </summary>
        public static string OverlayInfoNeeds {
            get {
                return ResourceManager.GetString("OverlayInfoNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell to Trader : {0}.
        /// </summary>
        public static string OverlayInfoSellToTrader {
            get {
                return ResourceManager.GetString("OverlayInfoSellToTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell to Trader Price : {0}.
        /// </summary>
        public static string OverlayInfoSellToTraderPrice {
            get {
                return ResourceManager.GetString("OverlayInfoSellToTraderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Price : {0}.
        /// </summary>
        public static string OverlayInfoWeekPrice {
            get {
                return ResourceManager.GetString("OverlayInfoWeekPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press compare key..
        /// </summary>
        public static string PressCompareKey {
            get {
                return ResourceManager.GetString("PressCompareKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil.
        /// </summary>
        public static string Recoil {
            get {
                return ResourceManager.GetString("Recoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
